# Generated by Django 5.1.1 on 2025-05-04 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(upload_to='resources/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'ppt', 'pptx', 'odp', 'jpg', 'jpeg', 'png', 'gif', 'svg', 'webp', 'py', 'js', 'java', 'cpp', 'c', 'html', 'css', 'php', 'mp4', 'mov', 'avi', 'mkv', 'webm', 'mp3', 'wav', 'ogg', 'm4a', 'zip', 'rar', '7z', 'tar', 'gz'])], verbose_name='file')),
                ('resource_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('PRESENTATION', 'Presentation'), ('IMAGE', 'Image'), ('CODE', 'Code'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('ARCHIVE', 'Archive'), ('OTHER', 'Other')], default='DOCUMENT', max_length=20, verbose_name='resource type')),
                ('size', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='size')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='is favorite')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='download count')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(default='default-slug', max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, default='folder', max_length=50, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'resource category',
                'verbose_name_plural': 'resource categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'study group',
                'verbose_name_plural': 'study groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(default='default-slug', unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
    ]
