# Generated by Django 5.1.1 on 2025-05-04 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by'),
        ),
        migrations.AddField(
            model_name='resource',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resource.resourcecategory', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(related_name='study_groups', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.AddField(
            model_name='resource',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resource.studygroup', verbose_name='shared groups'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resource.tag', verbose_name='tags'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type'], name='resource_re_resourc_d4799d_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['uploaded_at'], name='resource_re_uploade_52208a_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_public'], name='resource_re_is_publ_6896a0_idx'),
        ),
    ]
