# Generated by Django 5.1.1 on 2025-05-04 11:03

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('file', models.FileField(upload_to='resources/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'jpg', 'png', 'py'])], verbose_name='file')),
                ('file_type', models.CharField(choices=[('DOC', 'Document'), ('PPT', 'Presentation'), ('IMG', 'Image'), ('CODE', 'Code')], max_length=10, verbose_name='file type')),
                ('size', models.PositiveIntegerField(default=0, help_text='Size in bytes', verbose_name='size')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('subject', models.CharField(max_length=50, verbose_name='subject')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'study group',
                'verbose_name_plural': 'study groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
            ],
            options={
                'verbose_name': 'study session',
                'verbose_name_plural': 'study sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_hours', models.PositiveIntegerField(default=0, verbose_name='study hours')),
                ('sessions_attended', models.PositiveIntegerField(default=0, verbose_name='sessions attended')),
                ('groups_joined', models.PositiveIntegerField(default=0, verbose_name='groups joined')),
                ('resources_shared', models.PositiveIntegerField(default=0, verbose_name='resources shared')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
            options={
                'verbose_name': 'user activity',
                'verbose_name_plural': 'user activities',
            },
        ),
    ]
