# Generated by Django 5.1.1 on 2025-05-04 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_uploaded_resources', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(related_name='dashboard_study_groups', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.AddField(
            model_name='resource',
            name='groups',
            field=models.ManyToManyField(related_name='dashboard_resources', to='dashboard.studygroup', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='dashboard_attended_sessions', to=settings.AUTH_USER_MODEL, verbose_name='attendees'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dashboard.studygroup', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_activity', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
