# Generated by Django 5.1.1 on 2025-05-04 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studygroup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='user',
            field=models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='group_chats', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='chat',
            field=models.ForeignKey(help_text='Chat message this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='studygroup.groupchat', verbose_name='chat'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(help_text='User who is a member of the group', on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships_set', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='session',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='creator',
            field=models.ForeignKey(help_text='User who created this group', on_delete=django.db.models.deletion.PROTECT, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(help_text='Users who are members of this group', related_name='study_groups_set', through='studygroup.GroupMembership', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.AddField(
            model_name='session',
            name='group',
            field=models.ForeignKey(help_text='Group this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='studygroup.studygroup', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(help_text='Group the user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships_set', to='studygroup.studygroup', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='group',
            field=models.ForeignKey(help_text='Group this chat belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='studygroup.studygroup', verbose_name='group'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='studygroup__name_ddf417_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='studygroup__code_2dc645_idx'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='subject',
            field=models.ForeignKey(help_text='Primary subject area of the group', on_delete=django.db.models.deletion.PROTECT, related_name='study_groups', to='studygroup.subject', verbose_name='subject'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['start_time'], name='studygroup__start_t_2c4be7_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status'], name='studygroup__status_04aa16_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['role'], name='studygroup__role_bbfeed_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['is_active'], name='studygroup__is_acti_bed00b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('user', 'group')},
        ),
        migrations.AddIndex(
            model_name='groupchat',
            index=models.Index(fields=['group', 'created_at'], name='studygroup__group_i_c32580_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['privacy'], name='studygroup__privacy_5d2a13_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['created_at'], name='studygroup__created_576806_idx'),
        ),
    ]
